### PR TITLE
when reflecting a sdblob, insert all the stream and intermediate blobs using a transaction

### PR DESCRIPTION
**Pull request by shyba**

### CODE REVIEW

**Comment by kauffj** [comment]
what's blocking this?

**Comment by lyoshenka** [comment]
it should be deployed when niko has a chance to keep an eye on performance. if doing all these transactions causes problems, it will need to be rolled back

**Comment by lyoshenka** [comment]
wait, this can be closed in favor of #51

**Comment by lyoshenka** [comment]
or rather one of these should be closed and the other merged

**Comment by shyba** [comment]
closing this one as the other looks better and solves the same problem

**Pull request closed without merging**
